/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;
/* Header for class com_baurasia_pranav_digimother_OpencvNativeClass */

#ifndef _Included_com_baurasia_pranav_digimother_OpencvNativeClass
#define _Included_com_baurasia_pranav_digimother_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baurasia_pranav_digimother_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */

int toGray(Mat img, Mat& gray);
static void cutTable( Mat& image, const vector<vector<Point> >& squares );

JNIEXPORT jint JNICALL Java_com_baurasia_pranav_digimother_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

int toSquares(Mat img, Mat& imgWithSq);

JNIEXPORT jint JNICALL Java_com_baurasia_pranav_digimother_OpencvNativeClass_findSquares
        (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_baurasia_pranav_digimother_OpencvNativeClass_cropTable
        (JNIEnv *, jclass, jlong, jlong);
#ifdef __cplusplus
}
#endif
#endif
