/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baurasia_pranav_digimother_OpencvNativeClass */

#ifndef _Included_com_baurasia_pranav_digimother_OpencvNativeClass
#define _Included_com_baurasia_pranav_digimother_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baurasia_pranav_digimother_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_baurasia_pranav_digimother_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_baurasia_pranav_digimother_OpencvNativeClass
 * Method:    findSquares
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_baurasia_pranav_digimother_OpencvNativeClass_findSquares
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
